### ISSUE TITLE
Tasklist

### ISSUE THREAD

**Issue by mattiacolombomc** [PiervitoCreanza/IS24-AM02#106]
### Current tasks
- [x] Save running IDEA configurations (XML) in the repo to make them available to each member of the team _(handy!)_
- [x] Check if UML diagrams for Model and Network are up-to-date
- [x] Generate UML diagrams from IntelliJ and attach them to the final delivery
- [x] Clean up branches
- [x] Deactivate logger?
 - [x] #125
 - [x] #138 
 - [x] #162 
 - [x] Latest JAR?
 - [x] GitHub releases or GIT LFS for JARs? 
 - [x] If GIT LFS, add in README
---
### Model
- [x] #121

### Controller
- [x] #131
- [x] #113 
- [x] When a player is not connected, the controller should be able to end his turn and skip it until he reconnects.

### Network
- [x] #129 
- [x] #128 
- [x] #123
- [x] Investigate possible TCP clients "double disconnections". During testing we discovered that in rare cases the server is notified two times even if the client is only one.
- [x] Refactor messages, maybe we can only send gameName and playerName when a player creates or joins a game.
- [x] #122
 - [x] #101 
 - [x] #54 

- [x] Finish deleteGame() method implementation (both `TCP`/ `RMI`) #97 
 - [x] _"Delete"_ the game when `gameOver` #97 
      _While in `WAITING_FOR_PLAYERS` the host has a button to delete the game, then at the end of a game, when you go into Game Over, on the server you can delete the game_ 
      _"Delete"_ aka **remove** from `private final HashMap<String, HashMap<String, ServerMessageHandler>>         gameConnectionMapper;`

### GUI
- [x] Implement design

### Others
- [x] Save running IDEA configurations (XML) in the repo to make them available to each member of the team _(handy!)_
- [x] Prettify debug messages and add a CLI parameter on both Client and Server #103 

- [x] Update README

### Branches management
- [x] merge `simo_RMI` on `mc_RMI ` (check if this could cause conflicts!)
- [x] keep the RMI implementation branch without deleting the RMI "without callbacks" implementation
- [x] merge `implement-game` on `main`
- [x] #120
- [x] merge `mc_RMI` on `shared_network` AFTER merging @simonecurci and @Krema28
    - [x] `//TODO: gather arguments on updated VirtualView` in `Client.java`
- [x] rename existing branches, delete unuseful ones

_Feel free to add more._
