### ISSUE TITLE
Real-world testing checklist

### ISSUE THREAD

**Issue by mattiacolombomc** [PiervitoCreanza/IS24-AM02#152]
- [x] Try to connect with RMI to Server (may be Pier's one with the right open ports). At this stage we weren't able to do it, maybe a port opening port on Pier's side?
- [x] Toast notiifcation is bugged:
![CleanShot 2024-06-17 at 23 37 38@2x](https://github.com/PiervitoCreanza/IS24-AM02/assets/55593934/f0a2cc70-13a4-4b56-961f-80469ad28b5f)
- [x] Fix icons
![CleanShot 2024-06-17 at 23 39 38@2x](https://github.com/PiervitoCreanza/IS24-AM02/assets/55593934/b37b2c9e-4a9d-42fb-ad9e-67090a364825)
- [x] All the backs MUST be fixed, interval coding to color doesn't work
- [x] Players must be notified of LAST TURN
- [x] Avoid last player having to draw a card before showing the leaderboard
